### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by front-ck996** [brawer/miniwfs#4]
Is the project abandoned?

**Comment by brawer** [comment]
Is there a specific issue?

**Comment by front-ck996** [comment]
tiles/castles/17/69585/46595/102/50.geojson
I want to get a vector picture

**Comment by brawer** [comment]
The server already renders PNG tiles. Instead of PNG, would you like to get a vector format? Which format specifically? MVT perhaps?

I'll gladly review patches (GitHub pull requests). It's probably not completely trivial on the coarse zoom levels, because other than with a raster PNG tile we can't draw all data into the output. But this has been solved elsewhere; see eg. [MapBox Tippecanoe](https://github.com/mapbox/tippecanoe). Its algorithm can probably be implemented in Go quite easily. Feel free to give it a try; I'm looking forward to your contribution!
